[project]
name = "2048env"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=1.26.0",
    "gymnasium>=0.29.0",
    "ray>=2.49.2",
]
